language: csharp

matrix:
    include:
        - os: linux      
          dist: trusty
          sudo: required
          mono: none
          env: DOTNETCORE=1
          dotnet: 1.0.0-rc3-004530
script:
    - ./check.sh
