language: csharp

martix:
    include:
        - os: linux      
          dist: trusty
          sudo: required
          mono: none
          env: DOTNETCORE=1
          dotnet: 1.0.0-preview2-003131
        - os: osx # OSX 10.11
          osx_image: xcode7.2
          dotnet: 1.0.0-preview2-003131

script:
    - pushd src/Wrhs.Tests
    - dotnet restore
    - dotnet test
    - popd